## Log level
## Either "none", "error", "debug", "info"
#loglevel = "none"

## Dry run
## Do not output anything or send email after fecthing the sources
#dry-run = false

## User Agent
## If you want to override the user agent, you can do it here
## The default is "multiple:goeland" with a signature to make it compatible with reddit
#user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/120.0"

## Do not sanitize input
## This is not sanitize (the default) any input.
## Use at your own risk as you will include everything from your sources, including scripts, etc.
## You can always sanitize afterwards with the 'sanitize' filter.
#unsafe-no-sanitize-filter = false

## Run all the pipes once at startup in daemon mode
#run-at-startup = false

## Purge days
## Number of days to keep the entries when the purge command is used
## Can be overrided by command line switch
#purge-days = 15

## Auto purge
## Automatically run the purge command after the run command
#auto-purge = false

[email]
host = "smtp.example.com"
port = 587
username = "user"
password = "pass"
## Include header in email
## Put a nice goeland logo in emails
#include-header = true

## Include footer in email
## Put "Sent with ❤️ by goeland in the bottom of HTML emails"
#include-footer = true

## Include title in header
#include-title = false

## Email timeout in milliseconds
#timeout-ms = 5000

## Logo file
#logo = internal:goeland.png

## Template file
#template = "/path/to/template.html"

[sources]

[sources.hackernews]
url = "https://hnrss.org/newest"
type = "feed"
# See doc for available filters
filters = ["all", "today"]
# Allow invalid certificates
allow-insecure = false

[pipes]

[pipes.hackernews]
#Either put disabled = true or prefix pipes with disalbed like this: disabled.pipes.hackernews
disabled = true
source = "hackernews"
destination = "email"
email_to = ["zeus@olympus.com", "athena@olympus.com"]
email_cc = ["apollo@example.com"]
email_bcc = ["hades@example.com"]
email_from = "HackerNews <goeland@example.com>"
#Default: you can use EntryTitle, SourceTitle and SourceName in the template
#email_title = "{{.EntryTitle}}"
