name: Docker images

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Get version
      id: vars
      run: |
        echo ::set-output name=BUILD_DATE::$(date +'%Y%m%d%H%M%S')
        echo ::set-output name=GIT_COMMIT::$(git rev-parse HEAD)
        echo ::set-output name=GIT_TAG::$(git describe --tags --abbrev=0)
    - name: Setup QEMU
      id: qemu
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
      with:
        platforms: all

    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

    - name: Login to Docker Hub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        build-args: |
          BUILD_DATE=${{ steps.var.outputs.BUILD_DATE }}
          GIT_COMMIT=${{ steps.var.outputs.GIT_COMMIT }}
          IMGUR_CLIENT_ID=${{ secrets.IMGUR_CLIENT_ID }}
        platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: |
          ghcr.io/slurdge/goeland:latest
          ghcr.io/slurdge/goeland:${{ steps.vars.outputs.GIT_TAG }}
          slurdge/goeland:latest
          slurdge/goeland:${{ steps.vars.outputs.GIT_TAG }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
